# 테스트 설정

name: conventional-changelog-firefanda workflows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test Code
    strategy:
      matrix:
        node_version:
          - 10
          - 12
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js v${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Checkout master
        run: git checkout HEAD
      - name: Install dependency
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test

